### ISSUE TITLE
Where's the installer for Stockpile-AE2?

### ISSUE THREAD

**Issue by Arudarin** [brisingraerowing/OC-Programs#1]
The installer for Stockpile-AE2 is a 0 byte file....

**Comment by brisingraerowing** [comment]
I’ve kinda stopped working on most things on here. I haven’t done much with OC lately. I probably should finish some of these projects. I just haven’t had the motivation or time to do so. I do have some uncommitted code for some newer stuff, though. My computer is also acting up and crashing, so I need to fix that first.

**Comment by Arudarin** [comment]
Ah. It would be awesome for you to commit the code that you do have. Also, how would you install it manually?

**Comment by brisingraerowing** [comment]
Copy stockpile.lua to the /bin directory and the stockpile directory to /lib.

Most of the newer code is for sorting things using OC Sensors (Villagers, Mini Moos Fluid Cows, MooFluids Fluid Cows), along with a few other random bits and bobs. Those are at varying stages of completion (the villager sorter is probably the most complex as I want it to sort by profession, career, and available trades). All of them have plugin support for handling what to do with the mobs that go through (e.g. teleport them using RFTools).

**Comment by Arudarin** [comment]
https://i.imgur.com/2CINZhX.png

Getting this error when doing that.

**Comment by brisingraerowing** [comment]
That should be fixed now.

**Comment by Arudarin** [comment]
Hm. Getting this after fixing that:
https://i.imgur.com/VTC6SCN.png


This is my current setup:
https://i.imgur.com/jm6eBm3.png

**Comment by brisingraerowing** [comment]
Try it with the new version. I no longer use AE2, so I don't have a testing setup. If the new version doesn't work, I'll have to ask on the discord to see what I'm goofing up.

EDIT: Just a moment. I just found the issue. Derp.

**Comment by brisingraerowing** [comment]
NOW it should work. God I can be an idiot sometimes.

**Comment by Arudarin** [comment]
I'm going to close this and make a seperate issue for this.
