### ISSUE TITLE
Stockpile getting stuck on "What do you want to do?"

### ISSUE THREAD

**Issue by Arudarin** [brisingraerowing/OC-Programs#2]
Just prints "What do you want to do?", does not let me give user input, and exits/times out.

https://i.imgur.com/CE0IHOA.gifv

**Comment by brisingraerowing** [comment]
Interesting. I’ll look into it.

**Comment by brisingraerowing** [comment]
I honestly have no idea as to what is wrong. I’ve tried several things and it doesn’t want to work. I’ll have to ask on the discord.

**Comment by brisingraerowing** [comment]
OK. I got it to allow input, but it appears the buffer library has a bug causing to to fail to index a mode table. I'll poke the devs on discord and see what's up. I am using a dev build with Project Red support added back in, though.

**Comment by Arudarin** [comment]
Alright! For reference, I am using the latest version of FTB Revelation 2.1.0

**Comment by brisingraerowing** [comment]
It now works up until you try to find an item. I’m going to rewrite that part soon to make it work better.

**Comment by Arudarin** [comment]
Alright!

**Comment by Arudarin** [comment]
Any news on the mode table?

**Comment by brisingraerowing** [comment]
Haven’t been able to get it working yet.

**Comment by Arudarin** [comment]
Any idea as to what's wrong?

**Comment by brisingraerowing** [comment]
I have no idea, and I'm not sure how to rewrite it. I've been rather busy with life lately, so I haven't been able to work on this for a while.

**Comment by brisingraerowing** [comment]
I don't use AE2 with channels, and I am currently designing a GUI based system for this that works with and without channels, so I have depreciated the project.

**Comment by brisingraerowing** [comment]
Also, AE2-RV6 broke the OC integration. That is fixed in dev, though, and I plan on using the new features (including the fluid stuff) for the GUI. It may take a while due to IRL commitments, though.
